$(function(){
	$(".content").children(".conlis").hover(function(){
		if($(this).has(".sameul")){
			$(this).children(".sameul").slideDown();
		}
	},function(){
		$(this).children(".sameul").slideUp();
	});
});
